name: Deploy on Github

on:
  push:
    branches:
      - main

permissions:
  actions: read
  contents: write
  id-token: write

jobs:
  build:
    uses: zktx-io/slsa-on-move/.github/workflows/generator_generic_slsa3.yml@main
    with:
      move-compiler: "sui"
      move-directory: "sui/serializer"
